spring.application.name=pricefy

spring.datasource.url=jdbc:postgresql://localhost:5432/[NOME DO BANCO]
spring.datasource.username=[USUARIO]
spring.datasource.password=[SENHA]
spring.jpa.hibernate.ddl-auto=update
server.port=8080