spring.application.name=pricefy

spring.datasource.url=jdbc:postgresql://localhost:5432/pricefy
spring.datasource.username=postgres
spring.datasource.password=Marcelo.123
spring.jpa.hibernate.ddl-auto=update
server.port=8080